### ISSUE TITLE
Cannot build torchsearchsorted under ubuntu 16.04

### ISSUE THREAD

**Issue by iago-lito** [aliutkus/torchinterp1d#3]
Following the instructions given [there](https://github.com/aliutkus/torchsearchsorted#installation), I get the following error running `python setup.py install`:

```
torchsearchsorted/cuda/searchsorted_cuda_kernel.cu(131): error: more than one instance of overloaded function "fmax" matches the argument list:
            function "fmax(double, double)"
            function "fmax(float, float)"
            argument types are: (int64_t, int64_t)

torchsearchsorted/cuda/searchsorted_cuda_kernel.cu(137): error: more than one instance of overloaded function "fmin" matches the argument list:
            function "fmin(double, double)"
            function "fmin(float, float)"
            argument types are: (int, int64_t)

2 errors detected in the compilation of "/tmp/tmpxft_0001f79e_00000000-6_searchsorted_cuda_kernel.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
```
The machine I try to compile it on is quite not up-to-date I think. However, I cannot upgrade it for I have no root access :\

    $ gcc --version
    gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
    Copyright (C) 2015 Free Software Foundation, Inc.

```
$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
```

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
```

Yet the hardware is good :P

```
$ nvidia-smi
Thu Mar 21 19:05:37 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:03:00.0 Off |                  N/A |
|  0%   29C    P0    57W / 250W |      0MiB / 11172MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

What should I do?

**Comment by aliutkus** [comment]
hi @iago-lito ,
I tried to modify the fmin and fmax to use std::min and std::max instead. Probably this was the pb

could you try again to pull and install ?

**Comment by iago-lito** [comment]
I did. Well, this step passed, but a whole bunch of new ones followed :\ See the complete output [here].

[here]: https://github.com/aliutkus/torchinterp1d/files/2995750/output.txt
Would it be a problem with compilers / cuda / python versions?

**Comment by aliutkus** [comment]
damn, which version of cuda are you using?

**Comment by iago-lito** [comment]
Wops, I didn't write the whole output, sorry for that:
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
```

**Comment by aliutkus** [comment]
I tried something else, sorry for the inconvenience. Could you please start again pulling `torchsearchsorted` and installing again ?

**Comment by iago-lito** [comment]
Not much [progress].. X)

[progress]: https://github.com/aliutkus/torchinterp1d/files/2996026/output.txt

**Comment by aliutkus** [comment]
are you using torch 1.0 ?

**Comment by iago-lito** [comment]
Yupe:
```
$ pip3 show torch
Name: torch
Version: 1.0.1.post2
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /usr/local/lib/python3.5/dist-packages
Requires: 
Required-by: 
You are using pip version 18.0, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by aliutkus** [comment]
OK, I'm sorry since I cannot reproduce the bug, I got difficulties fixing it.

Could you investigate the problem ? It seems to be around these `fmin` and `fmax` calls. Maybe you find some other way to do the same computations ? If you manage, I'd be glad to have a pull request

**Comment by iago-lito** [comment]
I understand. I'll do my best. But I won't if an simple upgrade fixes the error, and I will investigate this option first.
Thank you for support anyway :)

**Comment by avivajpeyi** [comment]
Hey I think I am getting a similar issue:

`
pytorch: 1.0.1
gcc (GCC) 6.4.0
g++ (GCC) 6.4.0
nvcc: V9.0.176
GPU name: Tesla P100-PCIE
`

`
$ python setup.py install
....
/home/avajpeyi/.conda/envs/venv/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:2082:1: note: candidate: template<pybind11::return_value_policy policy, class ... Args, class> pybind11::detail::unpacking_collector<policy> pybind11::detail::collect_arguments(Args&& ...)
 unpacking_collector<policy> collect_arguments(Args &&...args) {
 ^~~~~~~~~~~~~~~~~
/home/avajpeyi/.conda/envs/venv/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:2082:1: note:   template argument deduction/substitution failed:
error: command '/apps/skylake/software/core/cuda/9.0.176/bin/nvcc' failed with exit status 1
`

Has there been any progress with this? Im trying to build torchsearchsorted so that I can build and use torchinterp1d (thank you, @aliutkus btw for implementing these :D)

**Comment by aliutkus** [comment]
that was quick

yeah, this is all working on cuda 10. I did not test, but it's clearly a pity that such a stupid cast between integers is causing so much troubles. I apologize for this

**Comment by lkn2993** [comment]
I guess this implementation only works on cuda 10.
It doesn't build on cuda 9 or 8 version of pytorch, as it returns an invalid cast error.
python36\lib\site-packages\torch\lib\include\pybind11\cast.h(1439): error: expression must be a pointer to a complete object type

**Comment by aliutkus** [comment]
true, although having a cast that works on cuda < 10 is probably just a trivial change of one line. I'd welcome it gladly

**Comment by crvogt** [comment]
I've got the test.py case working in 16.04 with cuda9.2, as an FYI.
